### PR TITLE
fix: Prepend user site dir to sys.path

### PR DESCRIPTION
**Pull request by robertschweizer**
Work around https://github.com/qgis/QGIS/issues/55258

I believe this might be the reason for issues like https://github.com/UMEP-dev/UMEP-processing/issues/40 and https://github.com/UMEP-dev/UMEP-processing/issues/30.

### CODE REVIEW

**Review by sunt05 — APPROVED** [review]
Thanks for tracking down the cause! Happy to approve this.

**Comment by sunt05** [comment]
@biglimp it looks we need to introduce some automatic CI/CD workflow to test the PRs and other developments (e.g. via GitHub Actions). Just a thought - this can be done in a separate thread.

**Review by j3r3m1 — APPROVED** [review]

**Comment by biglimp** [comment]
Thanks. Again, I will make same changes in https://github.com/UMEP-dev/UMEP.

**Comment by robertschweizer** [comment]
Thanks for merging this so quickly! Will you also release a fixed version to the QGIS plugins registry?

**Comment by biglimp** [comment]
Yes, I can try to do that later today.

**Comment by robertschweizer** [comment]
That's great, thanks a lot! @biglimp

**Comment by robertschweizer** [comment]
@biglimp Thanks a lot for releasing version 2.0.13 yesterday! I can see it at https://plugins.qgis.org/plugins/processing_umep/

However, my QGIS doesn't show the new version, only version 2.0.10 from September: 
image

Clicking "Reload Repository" and showing experimental plugins does not help. 

Any idea what might be the cause? Should I open a QGIS issue about this?

**Comment by biglimp** [comment]
I see it. Try again. Maybe restart everything...

image

**Comment by robertschweizer** [comment]
Yay, I see it now as well. Maybe some cache or so that had to update. Thanks a lot again for the quick release!

**Pull request merged**
